version: '3'
services:
  webapp:
    build: .
    image: swghosh/exudos-web
    restart: unless-stopped
    ports:
      - "80:8080"
    depends_on:
      - emailer
      - database
    environment:
      # inter communication
      MONGO_HOST: database
      MONGO_USER: user
      MONGO_PASSWD: password
      MONGO_DB: exudos
      # inter communication
      EMAIL_URL: http://emailer:8080/email

  emailer:
    build: misc/emailer
    image: swghosh/exudos-emailer
    restart: unless-stopped
    # must include SMTP server and credential details
    env_file:
      - ../../misc/emailer.env
    
  database:
    image: mongo
    restart: unless-stopped
    volumes:
      - ../../data/db:/data/db